### ISSUE TITLE
Unit/definition of L

### ISSUE THREAD

**Issue by Jinyan-Yang** [khufkens/phenograss-example#2]
I probably misunderstood the code/instruction but in the readme Table, L was given as 2.499. However, in the fortran code, L is declared as an integer. It will make most sense to me if L is an integer, meaning the number of delayed days. But if that's the case, L cannot be 2.49. 

Even if L is the mean of a MCMC chain, it should still be rounded to an integer I guess. Could the L in the table means the same as in the Choler paper, the number of 8 days? Then 2.499 roughly means 20 days?

Here's the link to where L is declared. 

https://github.com/khufkens/phenograss-example/blob/8b573210e0d2c2ce175a41abfd82701216dfed22/phenograss.f90#L16

**Comment by khufkens** [comment]
L is a mean value of the mcmc chain and rounded
